services:
  server:
    image: server
    build:
      context: .
      dockerfile: ./server/Dockerfile 
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SERVER_ENV: ${SERVER_ENV}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      db:
        condition: service_healthy
  simulation:
    build:
      context: .
      dockerfile: ./simulation/Dockerfile
  db:
    image: postgres:15.1-alpine
    ports:
      - 5432:5432
    volumes:
      - app-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

volumes:
  app-db:
    external: true
